// react-tests/src/main.tsx
/**
 * React integration test application
 * Tests the @k8s-web/react library by listing Kubernetes namespaces
 */
import React, { useEffect, useState } from 'react';
import ReactDOM from 'react-dom/client';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { useNamespaces, configureK8sClient } from '@k8s-web/react';

// Configure the K8s client
configureK8sClient({
  baseURL: 'https://localhost:6443',
  token: 'secret-token',
  rejectUnauthorized: false,
});

// Create a query client
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      retry: 1,
      refetchOnWindowFocus: false,
    },
  },
});

function App() {
  const { data, isLoading, error } = useNamespaces();
  const [status, setStatus] = useState('Initializing...');

  useEffect(() => {
    if (isLoading) {
      setStatus('Loading namespaces...');
    } else if (error) {
      setStatus('Error loading namespaces');
    } else if (data) {
      setStatus(`Loaded ${data.items?.length || 0} namespaces`);
    }
  }, [isLoading, error, data]);

  return (
    <div style={styles.container}>
      <h1>React Integration Test</h1>
      <h2>@k8s-web/react</h2>

      <div style={styles.status}>
        <p>
          Status: <span id="status" style={styles.statusText}>{status}</span>
        </p>
      </div>

      <div style={styles.namespaces}>
        <h3>Kubernetes Namespaces</h3>
        {isLoading && <p id="loading">Loading...</p>}
        {error && (
          <p id="error" style={styles.error}>
            Error: {error.message}
          </p>
        )}
        {data && data.items && (
          <ul id="namespace-list" style={styles.list}>
            {data.items.map((ns) => (
              <li key={ns.metadata?.name} style={styles.listItem}>
                {ns.metadata?.name}
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  );
}

const styles = {
  container: {
    maxWidth: '800px',
    margin: '0 auto',
    padding: '20px',
    fontFamily: 'Arial, sans-serif',
  },
  status: {},
  statusText: {
    fontWeight: 'bold',
  },
  error: {
    color: 'red',
  },
  namespaces: {},
  list: {
    listStyleType: 'none',
    padding: 0,
  },
  listItem: {
    padding: '8px',
    borderBottom: '1px solid #eee',
  },
};

const root = ReactDOM.createRoot(document.getElementById('root')!);
root.render(
  <React.StrictMode>
    <QueryClientProvider client={queryClient}>
      <App />
    </QueryClientProvider>
  </React.StrictMode>
);

// angular-tests/src/main.ts
/**
 * Angular integration test application
 * Tests the @k8s-web/angular library by listing Kubernetes namespaces
 */
import { bootstrapApplication } from '@angular/platform-browser';
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { CoreV1Service, K8S_CLIENT_CONFIG, k8sClientInterceptor } from 'k8s-web-angular';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="container">
      <h1>Angular Integration Test</h1>
      <h2>@k8s-web/angular</h2>

      <div class="status">
        <p>Status: <span id="status">{{ status }}</span></p>
      </div>

      <div class="namespaces">
        <h3>Kubernetes Namespaces</h3>
        @if (loading) {
          <p id="loading">Loading...</p>
        }
        @if (error) {
          <p id="error" class="error">Error: {{ error }}</p>
        }
        @if (namespaces.length > 0) {
          <ul id="namespace-list">
            @for (namespace of namespaces; track namespace) {
              <li>{{ namespace }}</li>
            }
          </ul>
        }
      </div>
    </div>
  `,
  styles: [
    `
      .container {
        max-width: 800px;
        margin: 0 auto;
        padding: 20px;
        font-family: Arial, sans-serif;
      }
      .error {
        color: red;
      }
      #status {
        font-weight: bold;
      }
      ul {
        list-style-type: none;
        padding: 0;
      }
      li {
        padding: 8px;
        border-bottom: 1px solid #eee;
      }
    `,
  ],
})
export class AppComponent implements OnInit {
  private coreV1 = inject(CoreV1Service);

  status = 'Initializing...';
  namespaces: string[] = [];
  loading = false;
  error = '';

  ngOnInit() {
    this.loadNamespaces();
  }

  loadNamespaces() {
    this.loading = true;
    this.status = 'Loading namespaces...';

    this.coreV1.listCoreV1Namespace().subscribe({
      next: (result) => {
        this.namespaces = result.items?.map((ns) => ns.metadata?.name || '') || [];
        this.status = `Loaded ${this.namespaces.length} namespaces`;
        this.loading = false;
      },
      error: (err) => {
        this.error = err.message || 'Unknown error';
        this.status = 'Error loading namespaces';
        this.loading = false;
      },
    });
  }
}

bootstrapApplication(AppComponent, {
  providers: [
    provideHttpClient(withInterceptors([k8sClientInterceptor])),
    {
      provide: K8S_CLIENT_CONFIG,
      useValue: {
        baseURL: 'https://localhost:6443',
        token: 'secret-token',
        rejectUnauthorized: false,
      },
    },
  ],
}).catch((err) => console.error(err));
